#!/usr/bin/env bash

# The path to git checkout of github.com/srid/rib.
# As this script resides under this repo, it is simply the parent directory of it.
RIBDIR=$(cd `dirname $0` && pwd)

# If your program file is Main.hs set this to Main
MAIN="Main"

nix-shell ${RIBDIR}/default.nix --run \
  "ghcid --reload=${MAIN}.hs -c 'ghci -Wall -i${RIBDIR}/src ${MAIN}.hs' -T 'System.Environment.withArgs [\"serve\", \"-w\"] ${MAIN}.main'"
